"""xiugai table

Revision ID: c186a8f98c79
Revises: c17fe0e09d93
Create Date: 2020-08-20 14:49:05.421789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c186a8f98c79'
down_revision = 'c17fe0e09d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.drop_column('tb_user', 'is_commited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('is_commited', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('tb_user', 'contact_id')
    # ### end Alembic commands ###
