"""table2

Revision ID: d27bdb96639e
Revises: e0aa531c5655
Create Date: 2020-08-21 09:48:45.874430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd27bdb96639e'
down_revision = 'e0aa531c5655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('contact_id', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
