"""table1

Revision ID: e0aa531c5655
Revises: e33b2e9edd88
Create Date: 2020-08-21 09:47:57.781040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aa531c5655'
down_revision = 'e33b2e9edd88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('contact_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', 'contact_id')
    # ### end Alembic commands ###
